apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/nviduchi-tenant/devfile-sample-python-basic-1/devfile-sample-python-basic@sha256:335a6e7350a613503940f23e46c0f2e6bd7d32ab13abeaca37e272a32a641e90
        name: my-python
        resources: {}
status: {}
